#!/bin/bash

source=`pwd`
target=${LOCI_TARGET-/usr/tmp/$LOGNAME}

COMP=${LOCI_COMP-KCC}
ARCH=${LOCI_ARCH-`arch`}

mkdir -p $target
mkdir -p $target/Loci
mkdir -p $target/Loci/System
mkdir -p $target/Loci/Tools
#mkdir -p $target/Loci/hdf5CC
mkdir -p $target/Loci/lib

cd $target/Loci
echo ln -s $source/src/Makefile Makefile
ln -s $source/src/Makefile Makefile
echo ln -s $source/src/conf/Loci.conf Loci.conf
ln -s $source/src/conf/Loci.conf Loci.conf
echo ln -s $source/src/Install.bash Install.bash
ln -s $source/src/Install.bash Install.bash
echo ln -s $source/src/include include
ln -s $source/src/include include
echo cp $source/src/conf/${COMP}.conf comp.conf
cp $source/src/conf/${COMP}.conf comp.conf
echo cp $source/src/conf/${ARCH}.conf sys.conf
cp $source/src/conf/${ARCH}.conf sys.conf

cd lib
ln -s ../Tools/libTools.a libTools.a
ln -s ../System/libLoci.a libLoci.a
#ln -s ../hdf5CC/libhdf5CC.a libhdf5CC.a

cd $source/src/System
for i in *.h *.cc Makefile; do
echo ln -s `pwd`/$i $target/Loci/System/$i
ln -s `pwd`/$i $target/Loci/System/$i
done
cd ../Tools
for i in *.h *.cc *.c Makefile; do
echo ln -s `pwd`/$i $target/Loci/Tools/$i
ln -s `pwd`/$i $target/Loci/Tools/$i
done
#cd ../hdf5CC
#for i in *.h *.cc *.c Makefile; do
#echo ln -s `pwd`/$i $target/Loci/hdf5CC/$i
#ln -s `pwd`/$i $target/Loci/hdf5CC/$i
#done

echo "** Be sure to set LOCI_BASE=\"$target/Loci\" **"


