###############################################################################
#
# Copyright 2008-2026, Mississippi State University
#
# This file is part of the Loci Framework.
#
# The Loci Framework is free software: you can redistribute it and/or modify
# it under the terms of the Lesser GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# The Loci Framework is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Lesser GNU General Public License for more details.
#
# You should have received a copy of the Lesser GNU General Public License
# along with the Loci Framework.  If not, see <http://www.gnu.org/licenses>
#
###############################################################################

include $(LOCI_BASE)/Loci.conf
include $(LOCI_BASE)/version.conf

INCLUDES = -I$(TEST_BASE)/contrib/doctest -I$(LOCI_BASE)/include \
           -I$(TEST_BASE)/../src/FVMAdapt2/library
LIB_PATH = $(LOCI_BASE)/lib:$(LD_LIBRARY_PATH)
DY_PATH = $(LOCI_BASE)/lib:$(DYLD_LIBRARY_PATH)
SOURCES = test_fvmadapt_core.cc test_adaptation_behavior.cc \
          test_refinement_state.cc fixtures.cc \
          core_utils.cc plan_checks.cc replay_trace.cc example_artifacts.cc
OBJS = $(SOURCES:.cc=.o)

.PHONY: default examples list clean distclean FRC

default: TestResults

TestResults: test_fvmadapt_core.exe FRC
	@LD_LIBRARY_PATH=$(LIB_PATH) DYLD_LIBRARY_PATH=$(DY_PATH) \
	  ./test_fvmadapt_core.exe --check-only > test_fvmadapt_core.log 2>&1 || { \
	    status=$$?; \
	    cat test_fvmadapt_core.log; \
	    echo "FVMAdapt2Tests/Core/Adaptation/test_fvmadapt_core: FAILED!" > $@; \
	    cat $@; \
	    exit $$status; \
	  }
	@echo "FVMAdapt2Tests/Core/Adaptation/test_fvmadapt_core: PASSED!" > $@
	@cat $@

examples: test_fvmadapt_core.exe
	@rm -fr output
	@mkdir -p output
	LD_LIBRARY_PATH=$(LIB_PATH) DYLD_LIBRARY_PATH=$(DY_PATH) ./test_fvmadapt_core.exe --write-dir output

list: test_fvmadapt_core.exe
	LD_LIBRARY_PATH=$(LIB_PATH) DYLD_LIBRARY_PATH=$(DY_PATH) ./test_fvmadapt_core.exe --list

test_fvmadapt_core.exe: $(LOCI_BASE)/include/Config/version_info.h \
                        $(OBJS) $(LOCI_BASE)/lib/libfvmadapt2func.$(LIB_SUFFIX)
	$(LD) -o $@ $(OBJS) -L$(LOCI_BASE)/lib -lfvmadapt2func $(LIBS) $(LDFLAGS)

clean:
	rm -fr *.o *.exe *.d *.log *.log1 TestResults output

distclean: clean

FRC:

DEPEND_FILES=$(SOURCES:.cc=.d)

ifeq ($(filter $(MAKECMDGOALS),clean distclean ),)
-include $(DEPEND_FILES)
endif
