default:
	cd FVM; $(MAKE) ; cd ..
	cd Containers; $(MAKE) ; cd ..

clean:
	cd FVM; $(MAKE) clean; cd ..
	cd Containers; $(MAKE) clean; cd ..

distclean:
	cd FVM; $(MAKE) distclean; cd ..
	cd Containers; $(MAKE) distclean; cd ..

