default:
	cd FVM; $(MAKE) LOCI_BASE=$(LOCI_BASE); cd ..
	cd Containers; $(MAKE) LOCI_BASE=$(LOCI_BASE); cd ..

clean:
	cd FVM; $(MAKE) LOCI_BASE=$(LOCI_BASE) clean; cd ..
	cd Containers; $(MAKE) LOCI_BASE=$(LOCI_BASE) clean; cd ..

distclean:
	cd FVM; $(MAKE) LOCI_BASE=$(LOCI_BASE) distclean; cd ..
	cd Containers; $(MAKE) LOCI_BASE=$(LOCI_BASE) distclean; cd ..

