MPIRUN= $(MPI_RUN) -np 1
SERIALRUN= $(MPI_RUN) -np 1
LOCI_CMD_FLAGS= 

FLOWTEST= $(MPIRUN) ../../fluidTest $(LOCI_CMD_FLAGS) 
EXTRACT= $(SERIALRUN) $(LOCI_BASE)/bin/extract
NDIFF=$(TEST_BASE)/bin/ndiff


